# Default values for coopengo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


api:
  enabled: true
  replicaCount: 1
  mongodb:
    database: coog
  image:
    repository: coopengo/api
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 150Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


api_b2b_config:
  enabled: false
  replicaCount: 1
  image:
    repository: coopengo/api-b2b-config
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 32m
    #   memory: 256Mi
    # requests:
    #   cpu: 32m
    #   memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


api_b2c:
  enabled: false
  replicaCount: 1
  image:
    repository: coopengo/api-b2c
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 32m
    #   memory: 256Mi
    # requests:
    #   cpu: 32m
    #   memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

app_b2c:
  enabled: false
  replicaCount: 1
  image:
    repository: coopengo/app-b2c
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api-b2c.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


celery:
  enabled: true
  batch: 
    schedule: "0 20 * * *"
  image:
    repository: coopengo/app-coog
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  root_dir: /workspace/io
  workers: 4
  replicaCount: 1
  specificBatchConcurrency:
    enabled: true
  affinity: {}
  nodeSelector: {}
  resources:
    limits:
      cpu: 1
      memory: 300Mi
    requests:
      cpu: 400m
      memory: 300Mi
  tolerations: []
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 120
    timeoutSeconds: 10


coog:
  enabled: true
  root_dir: /workspace/io
  workers: 4
  log_level: INFO
  timeout: 3600
  replicaCount: 1
  external_postgres:
    enabled: false
  postgres:
    database: coog
  persistentVolume:
    enabled: true
    name: workspace-io
    io: /workspace/io/
    storageClass: nfs-client
    size: 10Gi
    claim:
      name: ""
  image:
    repository: coopengo/app-coog
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  securityContext:
    runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: coog.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


cron:
  enabled: true
  image:
    repository: coopengo/app-coog
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  root_dir: /workspace/io
  affinity: {}
  nodeSelector: {}
  resources:
    limits:
      cpu: 400m
      memory: 300Mi
    requests:
      cpu: 400m
      memory: 300Mi
  tolerations: []
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 120
    timeoutSeconds: 10

gateway:
  enabled: true
  external_mongodb:
    enabled: false
  whitelist:
  replicaCount: 1
  image:
    repository: coopengo/gateway
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: gateway.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 300Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  mongodb_user: "coog"
  mongodb_root_password: "coog"
  external_mongodb:
    enabled: false
    host: ""
    port: ""
  mongodb:
    database: coog
  jwt:
    encryption: secret
    expiration: 3600
  portal_url: https://coog.local
  gateway_url: https://coog.local
  extraEnv:
    BASE_PATH: "/gateway"
    COOG_TOKEN_MODULE: "false"
  entrypoint: "/gateway"
  coog_web_token: "coog"
  mongodb_user: "coog"
  mongodb_root_password: "coog"


jwt:
  internal:
    encryption: secret

paybox:
  enabled: false
  replicaCount: 1

  image:
    repository: coopengo/paybox
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: paybox.local
        paths: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 32m
    #   memory: 128Mi
    # requests:
    #   cpu: 32m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

portal:
  enabled: false
  replicaCount: 1
  image:
    repository: coopengo/portal
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: portal.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


postresql:
  enabled: true
  postgresqlDatabase: coog
  postgresqlUsername: coog
  postgresqlPassword: coog


static:
  enabled: true
  replicaCount: 1
  image:
    repository: coopengo/static
    tag: 2.6.0
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: static.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


unoconv:
  enabled: true
  replicaCount: 1
  image:
    repository: coopengo/unoconv
    tag: 2.6.0
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 5000
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


web:
  replicaCount: 1
  image:
    repository: coopengo/web
    tag: 2.6.3
    pullPolicy: Always
  imagePullSecrets:
    - name: dockerhub-coopengo
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: web.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

redis:
  enabled: true
  usePassword: false
  cluster:
    enabled: false
  rbac:
    create: true
  master:
    persistence:
      enabled: true

mongodb:
  enabled: true
  image:
    tag: "4.0.10-debian-9-r39"
  replicaSet:
    enabled: false
  usePassword: true
  mongodbUsername: coog
  mongodbPassword: coog
  mongodbDatabase: coog
  mongodbRootPassword: coog
