{{- if .Values.api_identity.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "full_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.api_identity.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "short_name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "short_name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.api_identity.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api_identity.image.repository }}:{{ .Values.api_identity.image.tag }}"
          imagePullPolicy: {{ .Values.api_identity.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            procMount: Default
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name:  MONGO_HOST
            {{- if not .Values.gateway.external_mongodb.enabled }}
              value: "{{ .Release.Name }}-mongodb"
            {{ else }}
              value: "{{ .Values.gateway.external_mongodb.host }}"
            {{- end }}
            - name:  MONGO_PORT
            {{- if not .Values.gateway.external_mongodb.enabled }}
              value: "{{ .Values.mongodb.service.port }}"
            {{ else }}
              value: "{{ .Values.gateway.external_mongodb.port }}"
            {{- end }}
            - name:  MONGO_DB_NAME
              value: "{{ .Values.api.mongodb.database }}"
            - name:  MONGO_USER
              value: "{{ .Values.gateway.mongodb_user }}"
            - name:  MONGO_PASSWORD
              value: "{{ .Values.gateway.mongodb_root_password }}"
            - name: COOG_URL
              value: "http://{{ .Release.Name }}-{{ .Chart.Name }}-coog"
            - name: COOG_DB_NAME
              value: "{{ .Values.coog.postgres.database }}"
            - name:  JWT_INTERNAL_ENCRYPTION
              value: "{{ .Values.jwt.internal.encryption }}"
            {{- if .Values.api_identity.extraEnv }}
            {{- range $key, $value := .Values.api_identity.extraEnv }}
            - name:  {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.api_identity.resources | nindent 12 }}
      {{- with .Values.api_identity.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api_identity.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api_identity.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
