{{- if .Values.app_b2c.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "full_name" . }}
  labels:
{{ include "chart_labels" . | indent 4 }}
spec:
  type: {{ .Values.app_b2c.service.type }}
  ports:
    - port: {{ .Values.app_b2c.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "short_name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
