{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coog.serviceAccountName" . }}
  labels:
{{ include "coog.labels" . | indent 4 }}
{{- end -}}
