{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "flower.serviceAccountName" . }}
  labels:
{{ include "flower.labels" . | indent 4 }}
{{- end -}}
